페이지 이름 변경에 따른 라우팅 정리와 페이지 추가
who-is-hu/Givven_FE pull request #13
Opened 2020-08-25 08:07 UTC by yachae85

asana : https://app.asana.com/0/1185459641905461/1190211920479001/f

2020-08-25 08:09 UTC, yachae85 commented
Draft로 만들라했는데 잘못만들었는데 어떻게 수정해요?

2020-08-25 09:28 UTC, who-is-hu commented on src/components/pages/MyPage/index.jsx
>    const { auth } = useParams();
필요 없지 이제 
mypage는 normal인 경우 밖에 없자나 삭제부탁

2020-08-25 09:29 UTC, who-is-hu commented on src/components/pages/DashBoard/index.jsx
> +  const { auth } = useParams();
auath 이름을 userType등으로 다 바꿔줘

2020-08-25 09:32 UTC, who-is-hu commented on src/Router.jsx
> +}
만들어 놓고 왜 안써 로그인이 필요한 페이지에 감싸줘야지
props으로 받지말고 useSelector써서 auth.user 가 null이 아닐때 올바르게 라우팅하는걸로
(헤더 바 코드 참조)
( 401 안쓰는건 따로페이지 만들기 귀찮아서 )

2020-08-25 09:33 UTC, who-is-hu commented on src/Router.jsx
> +const IsLoggedIn = ({component: Component, loggedin, ...rest}) => {
IsLoggedInRouter

2020-08-25 09:33 UTC, who-is-hu requested changes
싱글 커멘트들 수정 바람

2020-08-25 09:33 UTC, yachae85 commented on src/components/pages/MyPage/index.jsx
>    const { auth } = useParams();
삭제할라했는데 그냥 /mypage/seller 이런식으로 치고들어가면 어떻게 나오나 싶었거든 근데 생각해보니까 switch가 다 걸러주는거지?

2020-08-25 09:35 UTC, who-is-hu commented on src/Router.jsx
> +  />
만들어 놓고 왜 안써 로그인이 필요한 페이지에 감싸줘야지
props으로 받지말고 useSelector써서 auth.user 가 null이 아닐때 올바르게 라우팅하는걸로
(헤더 바 코드 참조)
( 401 안쓰는건 따로페이지 만들기 귀찮아서 )

2020-08-25 09:41 UTC, who-is-hu commented on src/components/pages/MyPage/index.jsx
>    const { auth } = useParams();
ㅇㅇ 지우고 테스트 해봐 직접

2020-08-25 09:44 UTC, yachae85 commented on src/components/pages/MyPage/index.jsx
>    const { auth } = useParams();
아 저거 넣은이유가 권한검사안하고 그냥 /mypage이런식으로 접근할 수 있게 했을때 seller나 charity권한을 가진 사람이 /mypage를 그냥 치면 접근가능할거같아서 normal권한 아니면 전부 다 404로 빠지게 막아둔거거든 테스트해보고싶은데 권한 갖고있는건 어떻게 해? api써서 로그인한다음에 그냥 쳐보면되나? 캐시저장하는거 해결됐다 했지?

2020-08-25 15:44 UTC, who-is-hu commented on src/components/pages/MyPage/index.jsx
>    const { auth } = useParams();
아사나 코멘트 참조
애초에 니가 말하는 권한이란게 그냥 지멋대로 주소창에치면 권한이 되버리잖아 그래서
권한검사 라우터를 만들라한거고 redux에 저장해둔 권한 체크하는거 그 코드는 헤더쪽을 보면됨

2020-08-25 15:45 UTC, who-is-hu commented
> Draft로 만들라했는데 잘못만들었는데 어떻게 수정해요?

![image](https://user-images.githubusercontent.com/6914465/91196646-60b55180-e735-11ea-9668-ae952034d790.png)

2020-08-25 15:54 UTC, who-is-hu commented
추가로 페이지들에 만들어둔 Layout 넣어줘

2020-08-26 02:38 UTC, who-is-hu commented on src/Router.jsx
> +  console.log(useSelector(state=>state.auth.user));
삭제

2020-08-26 02:50 UTC, who-is-hu commented
바통 터치

2020-08-27 01:35 UTC, who-is-hu approved these changes

2020-08-27 01:36 UTC, merged