Feature/itemdetail
who-is-hu/Givven_FE pull request #15
Opened 2020-08-26 07:51 UTC by yachae85

asana : 상품 상세페이지 DB 바인딩

2020-08-27 01:52 UTC, who-is-hu requested changes
useEffect 사용과 Layout 감싸기

2020-08-29 08:19 UTC, who-is-hu commented on src/components/pages/ItemDetailPage/index.jsx
> +      {user && PurchaseButton()}
이것먼보면 로그인 되있ㅇ스면 구매버튼을띄우는 걸로 해석됨
`user.type === 'charity'` 예를 열로 빼

2020-08-29 08:19 UTC, who-is-hu requested changes
ㅇ

2020-08-29 10:12 UTC, yachae85 commented on src/components/pages/ItemDetailPage/index.jsx
> +      {user && PurchaseButton()}
이거 너 헤더 코드 따라한건데 50번째줄 코드에 {if (user.type === 'charity')} 이걸 못쓰더라고 그래도 내가 잘못했던거일수도 있으니까 한번 더 확인해봄

2020-08-29 10:20 UTC, yachae85 commented on src/components/pages/ItemDetailPage/index.jsx
> +      {user && PurchaseButton()}
확실히 자고일어나니까 머리가 깨끗해지긴 한다 이말이야 확인해보셈 super sexy code

2020-08-29 11:04 UTC, who-is-hu approved these changes
ㅇ

2020-08-29 11:04 UTC, merged