메인 페이지 slick slider
who-is-hu/Givven_FE pull request #40
Opened 2020-09-01 11:22 UTC by HamInKyou

asana : https://app.asana.com/0/1185459641905461/1191497068980525/f

2020-09-02 08:53 UTC, who-is-hu commented on src/components/pages/MainPage/index.jsx
>      const fetchData = async () => {
옌 뭐야

2020-09-02 08:53 UTC, who-is-hu commented on src/components/pages/MainPage/index.jsx
>      const fetchData = async () => {
왜 있다말어

2020-09-02 08:53 UTC, who-is-hu requested changes
npm i --save 로 다시 설치해줄래
package.json 변경사항이 적용이 안됐음

2020-09-03 17:02 UTC, HamInKyou commented on src/components/pages/MainPage/index.jsx
>      const fetchData = async () => {
있다 말았다는게 무슨 소리????

2020-09-05 15:32 UTC, who-is-hu approved these changes

2020-09-05 15:33 UTC, merged